name: Build Windows, Linux, and macOS Executables with PyInstaller

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        artifact_name: [wcag_checker_windows, wcag_checker_linux, wcag_checker_macos]
        output_file: [wcag_checker_windows.zip, wcag_checker_linux.zip, wcag_checker_macos.zip]
        shell: [ bash ]
        include:
          - os: windows-latest
            artifact_name: wcag_checker_windows
            output_file: wcag_checker_windows.zip
          - os: ubuntu-latest
            artifact_name: wcag_checker_linux
            output_file: wcag_checker_linux.zip
          - os: macos-latest
            artifact_name: wcag_checker_macos
            output_file: wcag_checker_macos.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv sync
        shell: bash

      - name: Build executable with PyInstaller
        run: |
          uv run pyinstaller ./wcag_checker_extracted.spec
        shell: bash

      - name: Rename artifact
        run: |
          mv dist/wcag_checker.zip dist/${{ matrix.output_file }}
        shell: bash

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.output_file }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: wcag_checker_windows
          path: dist/

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: wcag_checker_linux
          path: dist/

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: wcag_checker_macos
          path: dist/

      - name: Create Release and Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/wcag_checker_windows.zip
            dist/wcag_checker_linux.zip
            dist/wcag_checker_macos.zip
          draft: false
          prerelease: false
          name: Release ${{ github.ref_name }}
          body: Automated release for ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
