name: Build Windows Executable with PyInstaller

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
        shell: bash

      - name: Build executable with PyInstaller
        run: |
          pyinstaller ./wcag_checker_extracted.spec
        shell: bash

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: wcag_checker.zip
          path: dist/wcag_checker.zip
      - name: Create Release and Upload Artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/wcag_checker.zip
          draft: false
          prerelease: false
          name: Release ${{ github.ref_name }}
          body: Automated release for ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
